### ISSUE TITLE
Cannot send messages in systemChannel. Doesn't mention missing perms

### ISSUE THREAD

**Issue by Cyakat** [TacticalGubbins/word-tracker#44]
```
/home/cyakat/word-tracker/bot.js:181
  await guild.systemChannel.send({embeds: [joinEmbed]});
                            ^

TypeError: Cannot read properties of null (reading 'send')
    at Client.<anonymous> (/home/cyakat/word-tracker/bot.js:181:29)
    at Client.emit (node:events:526:28)
    at Object.module.exports [as GUILD_CREATE] (/home/cyakat/word-tracker/node_modules/discord.js/src/client/websocket/handlers/GUILD_CREATE.js:22:14)
    at WebSocketManager.handlePacket (/home/cyakat/word-tracker/node_modules/discord.js/src/client/websocket/WebSocketManager.js:346:31)
    at WebSocketShard.onPacket (/home/cyakat/word-tracker/node_modules/discord.js/src/client/websocket/WebSocketShard.js:493:22)
    at WebSocketShard.onMessage (/home/cyakat/word-tracker/node_modules/discord.js/src/client/websocket/WebSocketShard.js:327:10)
    at callListener (/home/cyakat/word-tracker/node_modules/ws/lib/event-target.js:290:14)
    at WebSocket.onMessage (/home/cyakat/word-tracker/node_modules/ws/lib/event-target.js:209:9)
    at WebSocket.emit (node:events:526:28)
    at Receiver.receiverOnMessage (/home/cyakat/word-tracker/node_modules/ws/lib/websocket.js:1184:20)
```

**Comment by Cyakat** [comment]
how can a channel be the system channel and allow me to have permission to send messages but not be able to send messages in it?
