### ISSUE TITLE
Bot will still crash when joining a channel

### ISSUE THREAD

**Issue by Cyakat** [TacticalGubbins/word-tracker#45]
I don't know what is causing it

```/home/cyakat/word-tracker/node_modules/discord.js/src/structures/GuildMember.js:341
    if (!channel) throw new Error('GUILD_CHANNEL_RESOLVE');
                        ^

Error [GUILD_CHANNEL_RESOLVE]: Could not resolve channel to a guild channel.
    at GuildMember.permissionsIn (/home/cyakat/word-tracker/node_modules/discord.js/src/structures/GuildMember.js:341:25)
    at Client.<anonymous> (/home/cyakat/word-tracker/bot.js:206:16)
    at Client.emit (node:events:526:28)
    at Object.module.exports [as GUILD_CREATE] (/home/cyakat/word-tracker/node_modules/discord.js/src/client/websocket/handlers/GUILD_CREATE.js:22:14)
    at WebSocketManager.handlePacket (/home/cyakat/word-tracker/node_modules/discord.js/src/client/websocket/WebSocketManager.js:346:31)
    at WebSocketShard.onPacket (/home/cyakat/word-tracker/node_modules/discord.js/src/client/websocket/WebSocketShard.js:493:22)
    at WebSocketShard.onMessage (/home/cyakat/word-tracker/node_modules/discord.js/src/client/websocket/WebSocketShard.js:327:10)
    at callListener (/home/cyakat/word-tracker/node_modules/ws/lib/event-target.js:290:14)
    at WebSocket.onMessage (/home/cyakat/word-tracker/node_modules/ws/lib/event-target.js:209:9)
    at WebSocket.emit (node:events:526:28) {
  [Symbol(code)]: 'GUILD_CHANNEL_RESOLVE'
}```

**Comment by Cyakat** [comment]
I have no idea what is causing this still. Its not a lack of permissions or the channel not existing
